
import React from 'react';
import { View } from '../types';
import { Shield, FileText, Book, ArrowLeft, Server, Code, Image, Mic, Terminal } from 'lucide-react';

interface LegalDocsProps {
    view: View;
    onNavigate: (view: View) => void;
}

const LegalDocs: React.FC<LegalDocsProps> = ({ view, onNavigate }) => {
    const renderContent = () => {
        switch (view) {
            case View.POLICY:
                return (
                    <div className="space-y-6">
                        <div className="flex items-center mb-6">
                            <Shield className="w-8 h-8 text-blue-600 mr-3" />
                            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Privacy Policy</h1>
                        </div>
                        <div className="prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>Last updated: {new Date().toLocaleDateString()}</p>
                            <h3>1. Data Collection</h3>
                            <p>Zee Builder is designed with a privacy-first approach. Most application state, including your projects, tasks, and settings, is stored locally on your device using browser LocalStorage.</p>
                            <h3>2. AI Interactions</h3>
                            <p>When you use AI features (Chat, Builder, Studios), user inputs are transmitted to Google Gemini APIs to generate responses. These interactions are subject to Google's AI data policies.</p>
                            <h3>3. Authentication</h3>
                            <p>Currently, user authentication is simulated for demonstration purposes. No personal data is stored on remote servers controlled by Zee Builder.</p>
                            <h3>4. Third-Party Services</h3>
                            <p>If you connect external services (GitHub, Firebase, Supabase), interactions with those services are governed by their respective privacy policies. Your API keys are stored locally and are not collected by us.</p>
                        </div>
                    </div>
                );
            case View.TERMS:
                return (
                    <div className="space-y-6">
                        <div className="flex items-center mb-6">
                            <FileText className="w-8 h-8 text-purple-600 mr-3" />
                            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Terms of Service</h1>
                        </div>
                        <div className="prose dark:prose-invert max-w-none text-slate-600 dark:text-slate-400">
                            <p>Last updated: {new Date().toLocaleDateString()}</p>
                            <h3>1. Acceptance of Terms</h3>
                            <p>By accessing and using Zee Builder, you accept and agree to be bound by the terms and provision of this agreement.</p>
                            <h3>2. Use License</h3>
                            <p>Permission is granted to temporarily download one copy of the materials (information or software) on Zee Builder's website for personal, non-commercial transitory viewing only.</p>
                            <h3>3. Disclaimer</h3>
                            <p>The materials on Zee Builder's website are provided on an 'as is' basis. Zee Builder makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.</p>
                            <h3>4. Code Generation</h3>
                            <p>Code generated by Zee AI is provided for assistance purposes. You are responsible for reviewing, testing, and securing any code before deploying it to production environments.</p>
                        </div>
                    </div>
                );
            case View.DOCS:
                return (
                    <div className="space-y-8">
                        <div className="flex items-center mb-6">
                            <Book className="w-8 h-8 text-green-600 mr-3" />
                            <h1 className="text-3xl font-bold text-slate-900 dark:text-white">Documentation</h1>
                        </div>
                        
                        <section className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-gray-200 dark:border-slate-800">
                            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4 flex items-center">
                                <Code className="w-5 h-5 mr-2 text-blue-500" /> App Builder
                            </h2>
                            <p className="text-slate-600 dark:text-slate-400 mb-4">
                                The Builder is your main workspace. You can select a stack (React, Vue, Flutter, HTML) and use natural language to generate code.
                            </p>
                            <ul className="list-disc pl-5 space-y-2 text-sm text-slate-500 dark:text-slate-400">
                                <li><strong>Chat Mode:</strong> Describe your app features in the right-hand panel.</li>
                                <li><strong>Live Preview:</strong> See Web apps render instantly. Flutter apps link to external compilers.</li>
                                <li><strong>Project Management:</strong> Your work is autosaved. Use the "My Projects" modal to switch contexts.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-gray-200 dark:border-slate-800">
                            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4 flex items-center">
                                <Image className="w-5 h-5 mr-2 text-pink-500" /> AI Studios
                            </h2>
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                <div>
                                    <h3 className="font-bold text-slate-800 dark:text-slate-200 text-sm mb-2">Image Studio</h3>
                                    <p className="text-xs text-slate-500">Generate assets, edit images with prompts, or create logos. Supports up to 4K resolution with Zee Pro Image.</p>
                                </div>
                                <div>
                                    <h3 className="font-bold text-slate-800 dark:text-slate-200 text-sm mb-2">Video Studio</h3>
                                    <p className="text-xs text-slate-500">Create videos from text prompts using the Veo model. Supports Landscape (16:9) and Portrait (9:16).</p>
                                </div>
                            </div>
                        </section>

                         <section className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-gray-200 dark:border-slate-800">
                            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4 flex items-center">
                                <Mic className="w-5 h-5 mr-2 text-red-500" /> Voice & Audio
                            </h2>
                            <p className="text-slate-600 dark:text-slate-400 mb-4">
                                Engage in real-time conversations or generate speech files.
                            </p>
                             <ul className="list-disc pl-5 space-y-2 text-sm text-slate-500 dark:text-slate-400">
                                <li><strong>Live API:</strong> Low-latency WebSocket connection for voice-to-voice interaction.</li>
                                <li><strong>TTS:</strong> Convert text to high-quality audio files (WAV).</li>
                                <li><strong>Transcription:</strong> Upload audio files to get accurate text transcripts.</li>
                            </ul>
                        </section>

                        <section className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-gray-200 dark:border-slate-800">
                            <h2 className="text-xl font-bold text-slate-900 dark:text-white mb-4 flex items-center">
                                <Terminal className="w-5 h-5 mr-2 text-yellow-500" /> API for Developers
                            </h2>
                            <p className="text-slate-600 dark:text-slate-400 mb-4">
                                Build your own applications on top of Zee's AI infrastructure.
                            </p>
                            <div className="flex items-center justify-between bg-slate-100 dark:bg-slate-950 p-4 rounded-lg">
                                <p className="text-sm text-slate-600 dark:text-slate-400">
                                    Visit the <strong>API & Developers</strong> section to generate your API keys and view the SDK reference.
                                </p>
                                <button onClick={() => onNavigate(View.DEVELOPERS)} className="text-xs bg-blue-600 text-white px-3 py-1.5 rounded-md font-bold hover:bg-blue-500">
                                    Go to Developer Console
                                </button>
                            </div>
                        </section>
                    </div>
                );
            default:
                return null;
        }
    };

    return (
        <div className="max-w-4xl mx-auto animate-in fade-in duration-500 pb-20">
            <button 
                onClick={() => onNavigate(View.HOME)}
                className="mb-6 flex items-center text-slate-500 hover:text-blue-600 transition-colors"
            >
                <ArrowLeft className="w-4 h-4 mr-2" /> Back to Home
            </button>
            {renderContent()}
        </div>
    );
};

export default LegalDocs;