import React, { useEffect, useRef } from 'react';
import sdk from '@stackblitz/sdk';
import { ProjectFile, Stack } from '../../types';

interface StackBlitzPreviewProps {
    files: ProjectFile[];
    stack: Stack;
    className?: string;
}

const StackBlitzPreview: React.FC<StackBlitzPreviewProps> = ({ files, stack, className }) => {
    const embedRef = useRef<HTMLDivElement>(null);
    const vmRef = useRef<any>(null);

    useEffect(() => {
        if (!embedRef.current) return;

        const projectFiles: Record<string, string> = {};
        files.forEach(f => {
            // Remove leading slash if present
            const path = f.name.startsWith('/') ? f.name.slice(1) : f.name;
            projectFiles[path] = f.content;
        });

        // Determine template based on stack
        let template: 'create-react-app' | 'node' | 'javascript' | 'typescript' | 'html' = 'javascript';
        
        switch (stack) {
            case 'react':
            case 'react-ts':
                template = 'create-react-app';
                break;
            case 'nextjs':
                template = 'node'; // Next.js runs in Node container
                break;
            case 'vue':
                template = 'node'; // Vue CLI / Vite
                break;
            case 'html':
                template = 'html';
                break;
            case 'python':
                template = 'node'; // We can't run Python in StackBlitz easily without WebContainers setup, but let's default to Node for now or handle separately
                break;
            default:
                template = 'javascript';
        }

        // If it's a Node/Next/Vue project, we might need a package.json if not present
        if ((template === 'node' || template === 'create-react-app') && !projectFiles['package.json']) {
            let defaultPkg = {};
            
            if (stack === 'nextjs') {
                defaultPkg = {
                    name: "zee-nextjs",
                    version: "0.1.0",
                    scripts: { "dev": "next dev", "build": "next build", "start": "next start" },
                    dependencies: { "next": "latest", "react": "latest", "react-dom": "latest" }
                };
            } else if (stack === 'vue') {
                defaultPkg = {
                    name: "zee-vue",
                    version: "0.0.0",
                    scripts: { "dev": "vite", "build": "vite build", "preview": "vite preview" },
                    dependencies: { "vue": "^3.4.0" },
                    devDependencies: { "@vitejs/plugin-vue": "^5.0.0", "vite": "^5.0.0" }
                };
            } else {
                // Default to React
                defaultPkg = {
                    name: "zee-project",
                    version: "0.0.0",
                    scripts: { "start": "react-scripts start", "build": "react-scripts build" },
                    dependencies: { 
                        "react": "^19.2.1", 
                        "react-dom": "^19.2.1", 
                        "react-scripts": "5.0.1" 
                    }
                };
            }
            
            projectFiles['package.json'] = JSON.stringify(defaultPkg, null, 2);
        }

        sdk.embedProject(
            embedRef.current,
            {
                title: 'Zee Project',
                description: 'Generated by Zee Builder',
                template: template,
                files: projectFiles,
                settings: {
                    compile: {
                        trigger: 'auto',
                        clearConsole: false,
                    },
                },
            },
            {
                height: '100%',
                width: '100%',
                hideExplorer: true,
                hideNavigation: false,
                forceEmbedLayout: true,
            }
        ).then(vm => {
            vmRef.current = vm;
        });

    }, [files, stack]);

    // Update files when they change
    useEffect(() => {
        if (vmRef.current) {
            const projectFiles: Record<string, string> = {};
            files.forEach(f => {
                const path = f.name.startsWith('/') ? f.name.slice(1) : f.name;
                projectFiles[path] = f.content;
            });
            vmRef.current.applyFsDiff({
                create: projectFiles,
                destroy: [], // We don't track deletions yet
            });
        }
    }, [files]);

    return <div ref={embedRef} className={className} style={{ height: '100%', width: '100%' }} />;
};

export default StackBlitzPreview;
